language: objective-c
osx_image: xcode7.2

script:
- xcodebuild -scheme Hookah -project Hookah.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S' ONLY_ACTIVE_ARCH=NO clean build test

after_success:
  - bash <(curl -s https://codecov.io/bash)
